config/routes.rb
Rails.application.routes.draw do
  root 'websites#new'

  resources :websites do 
    resources :links, shallow: true
  end

end 

#  Prefix Verb   URI Pattern                               Controller#Action
#             root GET    /                                         websites#new
#    website_links GET    /websites/:website_id/links(.:format)     links#index
#                  POST   /websites/:website_id/links(.:format)     links#create
# new_website_link GET    /websites/:website_id/links/new(.:format) links#new
#        edit_link GET    /links/:id/edit(.:format)                 links#edit
#             link GET    /links/:id(.:format)                      links#show
#                  PATCH  /links/:id(.:format)                      links#update
#                  PUT    /links/:id(.:format)                      links#update
#                  DELETE /links/:id(.:format)                      links#destroy
#         websites GET    /websites(.:format)                       websites#index
#                  POST   /websites(.:format)                       websites#create
#      new_website GET    /websites/new(.:format)                   websites#new
#     edit_website GET    /websites/:id/edit(.:format)              websites#edit
#          website GET    /websites/:id(.:format)                   websites#show
#                  PATCH  /websites/:id(.:format)                   websites#update
#                  PUT    /websites/:id(.:format)                   websites#update
#                  DELETE /websites/:id(.:format)                   websites#destroy

app/models/destroy.rb
class Destroy < ActiveRecord::Base
end

app/models/link.rb
class Link < ActiveRecord::Base
	belongs_to :website
end

app/models/website.rb
class Website < ActiveRecord::Base
	has_many :links, dependent: :destroy
	validates :site_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	before_action :find_website
	
  def index
    @doc = Nokogiri::HTML(open(@website.site_url))
    @links = []
    @anchors = @doc.css("a")
    # binding.pry
    # loop through the anchor tags and put all the urls into an array.

    @anchors.each do |anchor|
      if anchor.attr("href").include?("http") || anchor.attr("href").include?("https")
      @links << anchor.attr("href")
      end 
    end
    #binding.pry
  end

  def create 
  	@link = Link.create(link_params)
  	# redirect_to index_path
  end 

  def show
  end

 private 


  def find_website
  	@website = Website.find_by_id(params[:website_id])
  end 
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController

  def new
  	@website = Website.new
  	render :index 
  end

  def create 
  	@website = Website.create website_params
  	if @website.save
  		redirect_to website_links_path @website
  	else 
  		render :index
  	end
  end 

 private 
  def website_params
  	params.require(:website).permit(:site_name, :site_url)
  end

  # def find_website
  # 	@website = Website.find params[:website_id]
  # end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SidekiqLinkChecker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/edit.html.erb
<h1>Links#edit</h1>
<p>Find me in app/views/links/edit.html.erb</p>

app/views/links/index.html.erb
<h1><%= @website.site_name %>'s Index of Links</h1>
<p><%= @website.site_url %></p>

<%= @links.each do |link| %>
<p><%= link %></p>
<% end %>

app/views/links/new.html.erb
h1>New Link</h1>

<%= form_for(@link, url: new_path) do |f| %>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url autofocus: true %>
  </div>
  
  <div class="actions"><%= f.submit "Submit Link" %></div>
<% end %>

app/views/links/show.html.erb
<h1>One Website with Many Links</h1>
<p>Find me in app/views/links/show.html.erb</p>

app/views/websites/index.html.erb
<h1>Website Index and New</h1>

<%= form_for(@website, url: websites_path) do |f| %>
  <div class="field">
    <%= f.label :site_name %><br />
    <%= f.text_field :site_name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :site_url %><br />
    <%= f.text_field :site_url %>
  </div>
  
  <div class="actions"><%= f.submit "Submit" %></div>
<% end %>